
import './globals.css'
import { Inter } from 'next/font/google'
import Header  from './header/Header'
import Prov from '@/Provider'
import { Grid } from '@mui/material'
import { Sidebar, SmallSidebar } from './components/sidebar'
import ResponsiveSidebar from './components/responsiveSidebar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
    
      <body className={inter.className}>
      <Prov>
      <header><Header /> </header>

    <ResponsiveSidebar /> 
     {children}

      </Prov>
      </body>
      
    </html>
  )
}


